### ISSUE TITLE
Bug:  Subscription Exception and checkpoint

### ISSUE THREAD

**Issue by dthk-cogmatix** [Eventuous/eventuous#25] opened 2021-06-29 04:19 UTC
I think there is an issue where exceptions thrown in subscription handlers are NOT causing the checkpoint to be replayed from the last position.  

I think this is related to the SubscriptionService.cs: 108
`            Task Store() => StoreCheckpoint(GetPosition(re), cancellationToken);
`

I *believe* the GetPosition(re) should be _lastProcessed from line 90.

**Comment by alexeyzimarev** [comment] 2021-08-04 09:30
There was a bug that caused the dropped subscription to skip one event. It was fixed here: https://github.com/Eventuous/eventuous/commit/9f4cb7aebb7ff39c29d0e3679ae1a44697fbada7

There are two places where the subscription stores the checkpoint.

First is when a system event is ignored:
https://github.com/Eventuous/eventuous/blob/master/src/Eventuous.Subscriptions/SubscriptionService.cs#L78-L82

The second is after processing an event:
https://github.com/Eventuous/eventuous/blob/master/src/Eventuous.Subscriptions/SubscriptionService.cs#L106

In case of an exception in event processing, the `_lastPosition` is not updated and it's deliberate. This field is only used to report the processing gap. There's no intention in the code to retry processing the event as it's the responsibility of an event handler. If you want the subscription to throw and stop, you can set the `ThrowOnError` option to `true`.

So, how it's done now is by design. However, the next release would change the checkpoint management entirely. Therefore, I am closing this issue. The subscription docs would also be published only when the next release is out, as it makes no sense to document things that are going to change.

**Closed by alexeyzimarev** 2021-08-04 09:30 UTC
